### ISSUE TITLE
Force reimport fails

### ISSUE THREAD

**Issue by tfk-kaare** [TromsFylkestrafikk/ragnarok#95]
Trying to force re-import of existing data fails with the following error
```
The header record does not exist or is empty at offset: `0`
Occured in /home/kaare/src/ragnarok/vendor/league/csv/src/SyntaxError.php(44)
- #0 /home/kaare/src/ragnarok/vendor/league/csv/src/Reader.php(180): League\Csv\SyntaxError::dueToHeaderNotFound()
- #1 /home/kaare/src/ragnarok/vendor/league/csv/src/Reader.php(152): League\Csv\Reader->setHeader()
- #2 /home/kaare/src/ragnarok/vendor/league/csv/src/Reader.php(558): League\Csv\Reader->getHeader()
- #3 /home/kaare/src/ragnarok/vendor/league/csv/src/Reader.php(543): League\Csv\Reader->computeHeader()
- #4 /home/kaare/src/ragnarok/vendor/league/csv/src/Reader.php(451): League\Csv\Reader->prepareHeader()
- #5 /home/kaare/src/ragnarok/vendor/league/csv/src/Reader.php(322): League\Csv\Reader->getRecords()
- #6 /home/kaare/src/ragnarok/vendor/ragnarok/sink/src/Services/CsvToTable.php(226): League\Csv\Reader->getIterator()
- #7 /home/kaare/src/ragnarok-consat/src/Services/ConsatImporter.php(42): Ragnarok\Sink\Services\CsvToTable->exec()
- #8 /home/kaare/src/ragnarok-consat/src/Sinks/SinkConsat.php(60): Ragnarok\Consat\Services\ConsatImporter->import()
- #9 /home/kaare/src/ragnarok/app/Services/SinkHandler.php(174): Ragnarok\Consat\Sinks\SinkConsat->import() 
```

**Comment by tfk-kaare** [comment]
This is a duplicate of TromsFylkestrafikk/ragnarok-consat#17 fixed by TromsFylkestrafikk/ragnarok-sink#21
